title: 幸福猫 HappyCat
url: http://happycat.cc/

download_url: "https://anchor.fm/happycatpodcast"
subtitle: Happy Cat, Happy Life
description: 这是一档介绍华人旅德生活的播客。公众号：CC猫在德国
author: Yuchen
author_url: "http://happycat.cc/"

keywords: [Germany, Expat, WorkingInGermany, LivingInGermany, Chinese]
itunes_categories: [Technology]
episodes_per_feed_page: 10

player_theme: default # default | "default-dark" | legacy | minimal | republica

### Date can be localized via date_de.rb plugin, you don't need to change this
date_format: ordinal

language: en
explicit: "no" # "yes" | "no" | clean

### License Config, you really should configure this
license: CC BY-NC-ND
license_url: https://creativecommons.org/licenses/by-nc-nd/4.0
license_image_url: https://licensebuttons.net/l/by-nc-nd/3.0/88x31.png

### Feed links, optional
itunes_url: https://podcasts.apple.com/de/podcast/%E8%87%AA%E5%BE%97%E5%85%B6%E4%B9%90/id1526178818?l=en
google_play_url: https://www.google.com/podcasts?feed=aHR0cHM6Ly9hbmNob3IuZm0vcy8yYWQzOTgxNC9wb2RjYXN0L3Jzcw==
spotify_url: https://open.spotify.com/show/6H3y8zUN01RuPed94W23k6
breaker_url: https://www.breaker.audio/zi-de-qi-le
pocket_url: https://pca.st/ojwfex61
radiopublic_url: https://radiopublic.com/-GOVYml

theme: jekyll-bootflat

plugins:
  - jekyll-octopod

webrick:
  headers:
    Access-Control-Allow-Origin: "*"
    Access-Control-Request-Method: "GET"