# Site
name: "CC猫在德国"
title: "CC猫在德国"
description: "分享德国生活和工作的那些事情。"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
url: 'http://happycat.cc'
baseurl: ''
google_analytics: 'UA-46650228-1'
disqus: 'happycat-cc'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  CC猫饲养员1号:
    name: CC猫饲养员1号
    display_name: CC猫饲养员1号
    gravatar: 29a437715f46a307f6e500e86618618a
    email: thehappycatpodcast@gmail.com
    #web: https://happycat.cc
    twitter: https://twitter.com/senchan_sue
    description: "旅德程序员小姐姐"
  
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-5401904582868351"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

### Feed links, optional
itunes_url: https://podcasts.apple.com/de/podcast/%E8%87%AA%E5%BE%97%E5%85%B6%E4%B9%90/id1526178818?l=en
#google_play_url: https://www.google.com/podcasts?feed=aHR0cHM6Ly9hbmNob3IuZm0vcy8yYWQzOTgxNC9wb2RjYXN0L3Jzcw==
spotify_url: https://open.spotify.com/show/6H3y8zUN01RuPed94W23k6
pocket_url: https://pca.st/ojwfex61
radiopublic_url: https://radiopublic.com/-GOVYml
xiaoyuzhou_url: https://www.xiaoyuzhoufm.com/podcast/5f2970779504bbdb774de57d?s=eyJ1IjoiNWYyOTZmMmFlMGY1ZTcyM2JiYmNmZWNiIiwiZCI6MX0%3D

